
version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: <%= Rails.application.credentials.db[:password] %>
    ports:
      - "4306:3306"

  web:
    image: rails6
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  mysql-data:
    driver: local
